---
- hosts: proxy
  sudo: yes
  
  vars:
    shadowsocks_server_ip: "0.0.0.0"
    shadowsocks_server_port: "8388"
    shadowsocks_local_port: "1080"
    shadowsocks_timeout: "600"
    shadowsocks_encryption_method: "aes-256-cfb"

    shadowsocks_dependencies:
    - python-gevent
    - python-m2crypto
    - python-pip
    - qrencode
    
    shadowsocks_location: "/home/shadowsocks"
    shadowsocks_password_file: "{{ shadowsocks_location }}/shadowsocks-password.txt"
    shadowsocks_qr_code: "{{ shadowsocks_location }}/shadowsocks-qr-code.png"

  handlers:
    - name: Restart Shadowsocks
      service: name=shadowsocks
              state=restarted
              
  tasks: 
  - name: Install Shadowsocks dependencies
    apt: pkg={{ item }}
    with_items: "{{ shadowsocks_dependencies }}"

  - name: Add the Shadowsocks user
    user: name=shadowsocks
          home={{ shadowsocks_location }}
          shell=/usr/sbin/nologin
          comment="Shadowsocks User"

  - name: Generate a random Shadowsocks password
    shell: openssl rand -base64 24 > {{ shadowsocks_password_file }}
           creates={{ shadowsocks_password_file }}

  - name: Register Shadowsocks password
    command: cat {{ shadowsocks_password_file }}
    register: shadowsocks_password

  - name: Install Shadowsocks
    pip: name=shadowsocks

  - name: Generate Shadowsocks config file
    template: src=config.json.j2
              dest={{ shadowsocks_location }}/config.json
              owner=shadowsocks
              group=shadowsocks
              mode=640
    notify: Restart Shadowsocks

  - name: enable automatic start on system boot,
    command: sudo sed -i '/exit 0/ i /usr/bin/python /usr/local/bin/ssserver -c {{ shadowsocks_location }}/config.json -d start' /etc/rc.local


  - name: Generate the Shadowsocks QR code
    # The ss:// URI format is documented here:
    #   http://shadowsocks.org/en/config/quick-guide.html
    shell: echo -n '{{ shadowsocks_encryption_method }}:{{ shadowsocks_password.stdout }}@{{ ansible_default_ipv4.address }}:{{ shadowsocks_server_port }}' | base64 --wrap=0 | sed 's/^/ss:\/\//' | qrencode -s 15 -o {{ shadowsocks_qr_code }}
           creates={{ shadowsocks_qr_code }}

  - name: Set permissions on the QR code image and Shadowsocks password file
    file: path={{ item }}
          owner=shadowsocks
          group=shadowsocks
          mode=640
    with_items:
      - "{{ shadowsocks_password_file }}"
      - "{{ shadowsocks_qr_code }}"

  - name: Fetch the QR code image
    fetch: dest=/tmp/
           src={{ shadowsocks_qr_code }}
           flat=yes

  - name: Pause for explanation
    pause: prompt="Your randomly chosen Shadowsocks password is '{{ shadowsocks_password.stdout }}'. A custom QR code that can be used to automatically configure your Shadowsocks clients has been downloaded to /tmp/shadowsocks-qr-code.png. Simply scan this image to get up and running quickly. Look for the option when creating a new profile in the iOS and Android applications. Press any key to continue..."
